---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document: 
    keep_md: yes
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set( fig.path = "figs/fig-")

```

## Loading and preprocessing the data
```{r , echo=TRUE}
##Code for reading in the dataset and/or processing the data OK
#Load the necessary package
    library(tidyverse)
#Load the data
    activity <- read_csv("activity.csv")

```

## What is mean total number of steps taken per day?
```{r , echo=TRUE}

total_steps <- activity %>%
    #remove NA data
    drop_na(steps) %>% 
    #aggregate by date
    group_by(date) %>%  
    #calculate the total of steps per group
    summarise(mean_steps_day = sum(steps)) 
total_steps

##Histogram of the total number of steps taken each day
total_steps_hist <- ggplot(data = total_steps,aes(mean_steps_day) )+
                    geom_histogram(bins = 30, color = "black") +
                    labs(x = "Number of Steps",
                         y = "Date",
                         title = "Total steps per Day(excluding NA datas)")
total_steps_hist

##Mean and median number of steps taken each day
mean(total_steps$mean_steps_day)
median(total_steps$mean_steps_day)

```




## What is the average daily activity pattern?
```{r , echo=TRUE}
##Time series plot of the average number of steps taken

daily_activity <- activity %>%
    # remove NA
    drop_na() %>%
    # aggregate by interval
    group_by(interval) %>% 
    #calculate the mean steps per group 
    summarize(interval_steps = mean(steps))

#Creating a plot
    interval_steps_plot <- ggplot(daily_activity,
                                  aes(interval,interval_steps)) +
        geom_line(size = 1.0) +
        labs(x = "Interval", 
             y = "Steps", 
             title = "Average number of Steps per Interval" ) 
    interval_steps_plot
    
##The 5-minute interval that, on average, contains the maximum number of steps
daily_activity[which.max(daily_activity$interval_steps),]

```

## Imputing missing values
```{r , echo=TRUE}
#Calculate and report the total number of missing values
data_na <- sum(is.na(activity$steps))
print(data_na)

#filling in all of the missing values in the dataset
activity_fill <- activity %>% 
  fill(steps,.direction = "up") %>% 
    fill(steps)

#Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day.

#aggregate by date
total_steps2 <- activity_fill %>% 
group_by(date) %>%  
#calculate the total of steps per group
summarise(mean_steps_day = sum(steps)) 
total_steps2

##Histogram of the total number of steps taken each day
total_steps_hist2 <- ggplot(data = total_steps2 ,aes(mean_steps_day) )+
                    geom_histogram(bins = 30, color = "black") +
                    labs(x = "Number of Steps",
                         y = "Date",
                         title = "Total steps per Day(filled NA data)")
total_steps_hist

##Mean and median number of steps taken each day
mean(total_steps2$mean_steps_day)
median(total_steps2$mean_steps_day)


#Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

#They differs slightly.
#The mean of the first data excluding NA is 10766.19, the median is 10765.
#The mean of the second data filling the missing data is 9354.23, the median is 10395.

```


## Are there differences in activity patterns between weekdays and weekends?
```{r , echo=TRUE}
#Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

library(lubridate)
week_activity <- activity_fill %>% 
mutate(week_number = wday(date)) 

week_activity <- week_activity %>% 
mutate(key = if_else(week_number == c(1,7),"weekend","weekday"))

week_average <- week_activity %>%
  group_by(key,interval) %>% 
  summarize(average = mean(steps))
week_average
  
#Make a panel plot 
ggplot(week_average, aes(interval, average)) + 
        geom_line() + 
        facet_grid(key ~ .) +
        xlab("5-minute interval") + 
        ylab("avarage number of steps")


```


